version: "3.8"
services:
  db:
    container_name: sad
    image: postgres
    environment:
      POSTGRES_USER: yellowhatpro
      POSTGRES_DB: sad
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - sad-data:/data/db
volumes:
  sad-data: {}
