name: study-adda ci and push image to dockerhub and deploy on azure
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

defaults:
  run:
    working-directory: ./study-adda-backend

jobs:
  build_and_push:
    name: study-adda-ci
    environment: dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check path
        run: ls
      - name: Build docker image
        run: docker build -t yellowhatpro/study-adda .
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to dockerhub
        run: docker push yellowhatpro/study-adda
      - name: Render deploy trigger
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
